name: Release

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

permissions: 
  contents: read


jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    environment:
      name: production

    defaults:
      run:
        working-directory: app

    permissions:
      contents: read

    env:
      FLUTTER_VERSION: "3.41.9"
      JAVA_VERSION: "21"


    steps:
        
      - name: Checkout private Flutter repository
        uses: actions/checkout@v6
        with: 
          repository: ${{ secrets.SECRET_NAME }}/${{ secrets.REPO }}
          ref: main
          token: ${{ secrets.REPO_T }}
          # path: app


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
         

      - name: Restore pub packages
        run: |
            flutter pub get
      
          
      - name: Create .env.prod
        run: |
          cat > .env.prod << EOF
          COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }}
          COGNITO_REDIRECT_URL=${{ secrets.COGNITO_REDIRECT_URL }}
          COGNITO_LOGOUT_URI=${{ secrets.COGNITO_LOGOUT_URI }}
          COGNITO_DOMAIN=${{ secrets.COGNITO_DOMAIN }}
          EOF


      - name: Analyze project
        run: |
            flutter analyze --no-fatal-infos
            # flutter analyze


      - name: Run tests
        run: flutter test


      
      # -----------------------------------------
      # 6. CocoaPods
      # -----------------------------------------     

      - name: Install CocoaPods
        working-directory: app/ios
        run: pod install

        
      # -----------------------------------------
      # 7. Create temporary keychain
      # -----------------------------------------

      - name: Create temporary keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |

          KEYCHAIN_PATH="$RUNNER_TEMP/app-signing.keychain-db"

          security delete-keychain "$KEYCHAIN_PATH" 2>/dev/null || true
  
          security create-keychain \
            -p "$KEYCHAIN_PASSWORD" \
            "$KEYCHAIN_PATH"

          security set-keychain-settings \
            -lut 21600 \
            "$KEYCHAIN_PATH"

          security unlock-keychain \
            -p "$KEYCHAIN_PASSWORD" \
            "$KEYCHAIN_PATH"

          security list-keychains \
            -d user \
            -s "$KEYCHAIN_PATH"



      # -----------------------------------------
      # 8. Decode certificate
      # -----------------------------------------

      - name: Decode Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BC_BASE64 }}
        run: |

          CERTIFICATE_PATH="$RUNNER_TEMP/build_certificate.p12"

          echo -n "$BUILD_CERTIFICATE_BASE64" \
            | base64 --decode \
            -o "$CERTIFICATE_PATH"




      # -----------------------------------------
      # 9. Import certificate
      # -----------------------------------------

      - name: Import Apple certificate
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |

          CERTIFICATE_PATH="$RUNNER_TEMP/build_certificate.p12"

          KEYCHAIN_PATH="$RUNNER_TEMP/app-signing.keychain-db"

          security import \
            "$CERTIFICATE_PATH" \
            -P "$P12_PASSWORD" \
            -A \
            -t cert \
            -f pkcs12 \
            -k "$KEYCHAIN_PATH"

          security set-key-partition-list \
            -S apple-tool:,apple: \
            -k "$KEYCHAIN_PASSWORD" \
            "$KEYCHAIN_PATH"

          security list-keychain \
            -d user \
            -s "$KEYCHAIN_PATH"




      # -----------------------------------------
      # 10. Decode provisioning profile
      # -----------------------------------------

      - name: Install provisioning profile
        env:
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.B_PROVISION_PROFILE_BASE64 }}
        run: |

          PP_PATH="$RUNNER_TEMP/build_pp.mobileprovision"

          mkdir -p \
            "$HOME/Library/MobileDevice/Provisioning Profiles"

          echo -n "$BUILD_PROVISION_PROFILE_BASE64" \
            | base64 --decode \
            -o "$PP_PATH"

          cp \
            "$PP_PATH" \
            "$HOME/Library/MobileDevice/Provisioning Profiles/"









      # # -----------------------------------------
      # # 10.1. Install Apple certificate and provisioning profile
      # # -----------------------------------------

      
      - name: Install Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BC_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.B_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |

          CERTIFICATE_PATH="$RUNNER_TEMP/build_certificate.p12"

          PP_PATH="$RUNNER_TEMP/build_pp.mobileprovision"

          KEYCHAIN_PATH="$RUNNER_TEMP/app-signing.keychain-db"

          echo -n "$BUILD_CERTIFICATE_BASE64" \
            | base64 --decode \
            -o "$CERTIFICATE_PATH"

          echo -n "$BUILD_PROVISION_PROFILE_BASE64" \
            | base64 --decode \
            -o "$PP_PATH"

          security create-keychain \
            -p "$KEYCHAIN_PASSWORD" \
            "$KEYCHAIN_PATH"

          security set-keychain-settings \
            -lut 21600 \
            "$KEYCHAIN_PATH"

          security unlock-keychain \
            -p "$KEYCHAIN_PASSWORD" \
            "$KEYCHAIN_PATH"

          security import \
            "$CERTIFICATE_PATH" \
            -P "$P12_PASSWORD" \
            -A \
            -t cert \
            -f pkcs12 \
            -k "$KEYCHAIN_PATH"

          security set-key-partition-list \
            -S apple-tool:,apple: \
            -k "$KEYCHAIN_PASSWORD" \
            "$KEYCHAIN_PATH"

          security list-keychain \
            -d user \
            -s "$KEYCHAIN_PATH"

          mkdir -p \
            "$HOME/Library/MobileDevice/Provisioning Profiles"

          cp \
            "$PP_PATH" \
            "$HOME/Library/MobileDevice/Provisioning Profiles/"

      - name: Show signing identities
        run: |
          security find-identity \
            -v \
            -p codesigning \
            "$RUNNER_TEMP/app-signing.keychain-db"

      - name: Show provisioning profiles
        run: |
          ls -la \
            "$HOME/Library/MobileDevice/Provisioning Profiles"

      - name: Cleanup
        if: always()
        run: |
          security delete-keychain \
            "$RUNNER_TEMP/app-signing.keychain-db" \
            || true



      # -----------------------------------------
      # 11. Build IPA
      # -----------------------------------------



      

      # - name: Build iOS IPA
      #   run: |

      #     flutter build ipa \
      #       --release \
      #       --export-method app-store





        
      # - name: Build iOS App Bundle
      #   run: |
      #     flutter build ios \
      #       --release \
      #       --build-name=1.0.${{ github.run_number }} \
      #       --build-number=${{ github.run_number }} \
      #       --no-codesign


